name: Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme myst-parser
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e .
          
      - name: Debug package installation
        run: |
          python -c "import deeplib; print('Package path:', deeplib.__file__)"
          python -c "from deeplib.models.segmentation import UNet; print('Found UNet:', UNet)"
          
      - name: Build documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html -v
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2